### ISSUE TITLE
Why 9patch does not support multiple stretch regions

### ISSUE THREAD

**Issue by godcok** [romannurik/AndroidAssetStudio#87] opened 2016-01-08 13:57 UTC
Hello ,  why 9patch horizontal , vertical stretch regions does not support multiple

**Comment by romannurik** [comment] 2016-01-08 13:58
Duplicate of #11

**Closed by romannurik** 2016-01-08 13:58 UTC

**Comment by godcok** [comment] 2016-01-08 14:05
http://romannurik.github.io/AndroidAssetStudio/nine-patches.html   
this html does not support
