### ISSUE TITLE
lanucher icon can not center

### ISSUE THREAD

**Issue by huajianjiang** [romannurik/AndroidAssetStudio#173] opened 2017-08-26 06:21 UTC
![ic_my_wifi](https://user-images.githubusercontent.com/12984573/29739154-bdb5fc08-8a69-11e7-8dac-aaddd6b97974.png)

**Comment by mayanxoni** [comment] 2017-08-26 17:09
Yeah, that has happened to me before.

**Comment by ishitatsuyuki** [comment] 2017-09-15 11:35
I have also experienced this when using a SVG.

**Comment by Sakib-Rahman-Bangladesh** [comment] 2017-11-03 05:08
I'v faced the same.

**Comment by renanmedina** [comment] 2017-11-16 23:04
Can you provide the image you're using to generate your icon ? I would like to reproduce this problem and fix it. Thank you!

**Comment by Sakib-Rahman-Bangladesh** [comment] 2017-11-17 04:18
Quick reply: 
I solved my problem, but for better outcome i'll provide you image, during my project upgrade time.

Thanks for your collaboration.

**Comment by romannurik** [comment] 2019-05-16 17:43
Duplicate of #174

**Closed by romannurik** 2019-05-16 17:43 UTC
