### ISSUE TITLE
Support for generating adaptive icons

### ISSUE THREAD

**Issue by sampalmer** [romannurik/AndroidAssetStudio#156] opened 2017-04-21 22:04 UTC
Android O introduces [adaptive icons](https://developer.android.com/preview/features/adaptive-icons.html). Can you please add support for generating these?

**Comment by sami286** [comment] 2017-05-06 14:05
That would be awesome :smiley:

**Comment by romannurik** [comment] 2019-05-16 17:40
Duplicate of #160

**Closed by romannurik** 2019-05-16 17:40 UTC
