### ISSUE TITLE
Non-Square Image Resizer Tool

### ISSUE THREAD

**Issue by Pirdod** [romannurik/AndroidAssetStudio#134] opened 2017-01-20 20:17 UTC
Hi,

A feature that I've been waiting for as part of the AndroidAssetStudio is to be able to resize non-square assets. It doesn't necessarily have to be icons and it doesn't need such features as trimming and changing colors but it would be nice to be able to define the target width and height and download all the dpi-specific versions.

Is something like this a possibility in the future?
Thanks.

**Comment by romannurik** [comment] 2017-01-20 21:10
Duplicate of #9

**Closed by romannurik** 2017-01-20 21:10 UTC
