### ISSUE TITLE
Paint icon with color does not work no more

### ISSUE THREAD

**Issue by spartacus777** [romannurik/AndroidAssetStudio#76] opened 2015-10-29 10:50 UTC
When I use "generic icons" tool I can not paint icons with color (flat foreground color) - https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.space.trim=1&source.space.pad=0&size=24&padding=8&color=33b5e5%2C100&name=ic_example

Two months before I was able to do this, so there is a regression in last few commits maybe.
Please fix that, it is too critical thing for me.
Thanks!

**Comment by romannurik** [comment] 2015-10-29 11:02
Duplicate of #74

**Closed by romannurik** 2015-10-29 11:02 UTC

**Comment by spartacus777** [comment] 2015-10-29 11:08
I will try another browther then. Thanks for quick reply!

**Comment by spartacus777** [comment] 2015-10-29 11:10
Works in firefox. Thanks for ypour great tool one more time man!
