### ISSUE TITLE
Launcher icon generator circle error

### ISSUE THREAD

**Issue by hjwnet** [romannurik/AndroidAssetStudio#205] opened 2019-05-14 02:42 UTC
Launcher icon generator  here  **Shape:circle**  Generated=`web ico` and `web_hi_res_512.png` are **not circle** 

This problem has been happening for a long time, please fix it, thank you very much. 
your open source project is very powerful, thank you for your contribution!

**Comment by romannurik** [comment] 2019-05-14 03:03
Duplicate of #204

**Closed by romannurik** 2019-05-14 03:03 UTC
