### ISSUE TITLE
Add option to add second line in Text icon

### ISSUE THREAD

**Issue by prateekjaiswal** [romannurik/AndroidAssetStudio#163] opened 2017-06-08 19:15 UTC
I really love the tool and really appreciate effort you guys put in. It would be more useful if i have second line in text logo. Many application have long name e.g. "Diamond Crush" and that name doesn't fit in single line. 

I am also a developer, If someone can guide me i can also do it.

Rerefence : [https://www.norio.be/android-feature-graphic-generator/](https://www.norio.be/android-feature-graphic-generator/)

**Comment by romannurik** [comment] 2017-06-08 20:25
Duplicate of #33

**Closed by romannurik** 2017-06-08 20:25 UTC
