### ISSUE TITLE
adaptive icon generate online

### ISSUE THREAD

**Issue by 63bl39** [romannurik/AndroidAssetStudio#183] opened 2018-03-13 16:27 UTC
sir, could you make an adaptive icon generator online like your previous icon generator online?? please sir.
it's really help me and other people that want to create an icon but doesn't have a PC/laptop (including me). 
till now,I always using your icon generator online to create my icon, but when android O was coming I'm really stuck to create adaptive icon because there no mobile apps nor online tool for create adaptive icons, (wish I can buy a PC/laptop, but who am I? 😞).
(sorry for my bad english).

thank you in advance.
![screenshot_2018-03-13-22-59-12](https://user-images.githubusercontent.com/36222381/37355344-198dd228-2716-11e8-9181-d3919209f813.jpg)

**Comment by bpappin** [comment] 2018-05-30 12:54
I was just thinking how I'd live to see this tool updated. Thanks for that!

**Comment by bpappin** [comment] 2018-05-30 13:09
@tibbi no way to leave an issue on that fork you have going, but for some reason it's forcing a drop shadow on the layer, in addition to a long-shadow, which it shouldn't do.

**Comment by tibbi** [comment] 2018-05-30 13:33
well I dont plan working on it, but the original repo is using drop shadow too

**Comment by bpappin** [comment] 2018-05-30 13:36
interesting. its much more subtle. I'll fork it and see if I can adjust it myself. not a front end guy, but I'll see what I can do :)

**Comment by tibbi** [comment] 2018-05-30 13:45
Im not a frontend guy either, I used a few of those things for the first time in my life :)

**Comment by bpappin** [comment] 2018-05-30 13:51
Ok, this version generates the long shadow without the drop shadow.

https://github.com/bpappin/AndroidAssetStudio

**Comment by tibbi** [comment] 2018-05-30 13:54
I guess you havent commited your changes yet, you just use it locally.

**Comment by GabRobUK** [comment] 2019-03-22 09:20
Hi, not sure if it is just me but the launcher icon generator is not working. I now get a flat square version of the app icon (web_hi_res_512.png) for both the square and circle version. The interesting thing is that it does generates the right versions (and shapes) of the mipmaps. Can someone help?

**Comment by romannurik** [comment] 2019-03-22 11:04
This change is intentional, to align with the new Google Play icon requirements

**Comment by bpappin** [comment] 2019-03-22 16:17
Sorry @tibbi i didn't notice the comment all this time, and you are right I never committed it. 
It's probably too late now, but I have pushed it up to the fork, in case it's needed.

**Comment by romannurik** [comment] 2019-05-16 17:40
Duplicate of #160

**Closed by romannurik** 2019-05-16 17:40 UTC
