### ISSUE TITLE
This tool doesn't support more than 1 stretch marker.

### ISSUE THREAD

**Issue by richardlalancette** [romannurik/AndroidAssetStudio#185] opened 2018-04-09 14:22 UTC
You can create as many as 25 markers on a nine patch, this is falsely represented in this tool. No UI to create more patches...

**Comment by ptolp** [comment] 2018-04-19 11:28
+1 This would be required to create scalable speech bubble type of elements which are otherwise hard to create.

**Comment by romannurik** [comment] 2019-05-16 17:54
Duplicate of #11

**Closed by romannurik** 2019-05-16 17:54 UTC
Labels: area: 9-patch, enhancement
