### ISSUE TITLE
Export SVG file for Launcher Icon Generator

### ISSUE THREAD

**Issue by malloth** [romannurik/AndroidAssetStudio#67] opened 2015-09-25 13:31 UTC
It would be really nice to have a .svg and .xml (vector drawable) files in zip after creating launcher icon. With this I can later produce custom sized logo in Generic Icon Generator. I'd like to create a 144dp launcher icon for my splash screen and I'm unable to do this without .svg file.

**Comment by jangrewe** [comment] 2016-04-22 07:12
Oh yes, that would be awesome! I gather it's already working with SVG internally, so providing this as an output like the "web icon" would be very helpful.

@romannurik i'd try to add this myself and send you a PR, but unfortunately i can't get it to build because of flintjs =(

**Comment by romannurik** [comment] 2017-01-17 14:59
SVGs/vectors are actually pretty difficult to generate for anything except clipart, and also launcher icons have a ton of effects that can't easily be reproduced without some hefty SVG, so closing this as out of scope for now.

**Closed by romannurik** 2017-01-17 14:59 UTC
