### ISSUE TITLE
Colors not applied in new google chrome update

### ISSUE THREAD

**Issue by amehdi** [romannurik/AndroidAssetStudio#74] opened 2015-10-22 09:51 UTC
I don't know from which version this behavior begins; but currently in chrome version 46.0.2490.71 m (for windows) the custom color doesn't work neither in "Generic icons" nor in "Action Bar and Tab Icon".

**Comment by benleunginnopage** [comment] 2015-10-23 06:02
same issue with chrome 46.0.2490.71

**Comment by bill-mybiz** [comment] 2015-10-23 13:20
Same with 46.0.2490.80

**Comment by romannurik** [comment] 2015-10-25 03:12
Is this a duplicate of #71?

**Comment by amehdi** [comment] 2015-10-25 06:14
@romannurik Absolutely not! It is about color overlays.

**Comment by bill-mybiz** [comment] 2015-10-25 06:25
IMHI, the issue manifestation may not be a duplicate per se, but that they
both fail in chrome but succeed in other browsers and that it affects
colorization suggests that there is a good chance the root cause is related.

**Comment by romannurik** [comment] 2015-10-27 04:24
Which OS are you running Chrome on? Works fine on Chrome 46.0.2490.80 running on a Mac…

**Comment by benleunginnopage** [comment] 2015-10-27 04:26
Windows 7

**Comment by bill-mybiz** [comment] 2015-10-27 11:18
I'm on Windows 10.

**Comment by amehdi** [comment] 2015-10-27 11:53
mine is Windows 8.1
It seems we should mention someone from Google Chrome team here since its obviously a browser issue.

**Comment by tmdues** [comment] 2015-10-27 19:47
I'm seeing the same issue on chrome (46.0.2490.80) for Windows 7

**Comment by 3lywa** [comment] 2015-10-28 01:21
Same issue here on Windows 10 with Chrome 46.0.2490.80 m

**Comment by benleunginnopage** [comment] 2015-10-28 01:24
If mac is ok, then is it a chrome bug?

**Comment by vipulyaara** [comment] 2015-10-28 10:56
Same issue on Chrome Version 46.0.2490.71 m, Windows 8.1.

**Comment by garywzh** [comment] 2015-10-29 04:59
Same issue on Win7 with chrome 46.0.2490.80 m

**Comment by smrehan6** [comment] 2015-10-30 04:16
same here chrome Version 46.0.2490.80 m win7

**Comment by TomasValenta** [comment] 2015-10-30 08:00
Same on W10 and Chrome 46.0.2490.80 m

**Comment by RudolfHladik** [comment] 2015-11-04 09:36
same issue Version 46.0.2490.80 m, OS Win 10

**Comment by derAndroidPro** [comment] 2015-11-06 16:55
Same issue in Chrome on Windows 10: http://prntscr.com/8zr139

**Comment by easyaspi314** [comment] 2015-11-07 22:17
Same in 46.0.2490.80 m on Vista x86.

**Comment by easyaspi314** [comment] 2015-11-20 02:46
This is important: **It works on Opera 33.0**, same Chromium engine version (to the decimal point, 46.0.2490.86), same computer, side-by-side: 

![It works in opera](https://cloud.githubusercontent.com/assets/6258309/11290626/77aa22e4-8f06-11e5-91ab-5a37382aba7c.png)

Works: Opera 33.0.1990.115 - `Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115`
Doesn't work: Chrome 46.0.2490.80 m - `Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36`

**Comment by amehdi** [comment] 2015-12-03 07:11
It seems the problem solved in new release of chrome on windows (Version 47.0.2526.73 m).

**Comment by jon80** [comment] 2015-12-03 08:44
How was it resolved, please?

Date: Wed, 2 Dec 2015 23:11:34 -0800

**Closed** 2016-03-20 16:43 UTC
